// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-JdtIvyZstbo8kzepoTQWx5N8KT9DFGE',
    appId: '1:540993286777:web:5df030c426ea951f8a5aa8',
    messagingSenderId: '540993286777',
    projectId: 'my-ecommerce-app-123-5e725',
    authDomain: 'my-ecommerce-app-123-5e725.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-5e725.firebasestorage.app',
    measurementId: 'G-VJ0EJZFK2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUTWtmM7x6HKbhXqzFoGQlIDMEdqRBDpI',
    appId: '1:540993286777:android:98f89036b2aab3b18a5aa8',
    messagingSenderId: '540993286777',
    projectId: 'my-ecommerce-app-123-5e725',
    storageBucket: 'my-ecommerce-app-123-5e725.firebasestorage.app',
  );

}